@startuml

rectangle "Use case name: Add a product" {
    note
    <b>Related requirements:</b> R5
    <b>Goal in context:</b> A pharmacist adds medicine to the product catalog
    <b>Preconditions:</b> Action is limited to pharmacists
    <b>Successful end condition:</b> Medicine added to the catalog
    <b>Failed end condition:</b> N/A
    <b>Primary actors:</b> Pharmacist
    <b>Secondary actors:</b> N/A
    <b>Trigger:</b> Pharmacist requests system to add medicine to catalog
    <b>Main flow:</b> Pharmacist requests system to add medicine to catalog
               System presents an add product form
               Pharmacist enters the medicine's details
               System adds the medicine to the product catalog
               System displays a success message
    <b>Extensions:</b> N/A
    end note
}

@enduml
