@startuml

rectangle "Use case name: Search product" {
    note
    <b>Related requirements:</b> R6
    <b>Goal in context:</b> A pharmacist confirms whether some medicine is in the product catalog
    <b>Preconditions:</b> Action is limited to pharmacists
    <b>Successful end condition:</b> Yes/no confirmation of availability of the medicine
    <b>Failed end condition:</b> N/A
    <b>Primary actors:</b> Pharmacist
    <b>Secondary actors:</b> N/A
    <b>Trigger:</b> Pharmacist requests system search for some medicine
    <b>Main flow:</b> Pharmacist requests system search for some medicine
               System presents a search box and relevant filter options
               Pharmacist enters a query
               System checks the medicine's availability
               System displays a message showing the medicine's availability
    <b>Extensions:</b> N/A
    end note
}

@enduml
