@startuml

rectangle "Use case name: Account creation" {
    note
    <b>Related requirements:</b> R4
    <b>Goal in context:</b> A pharmacist creates account for customer
    <b>Preconditions:</b> N/A
    <b>Successful end condition:</b> New customer account created
    <b>Failed end condition:</b> N/A
    <b>Primary actors:</b> Pharmacist
    <b>Secondary actors:</b> N/A
    <b>Trigger:</b> Pharmacist requests system to create a new account
    <b>Main flow:</b> Pharmacist requests system to create a new account
               System presents an account creation form
               Pharmacist enters customer's details
               System creates a new account for the customer
               System displays a success message
    <b>Extensions:</b> N/A
    end note
}

@enduml
